DROP DATABASE IF EXISTS project_hotels;
CREATE DATABASE project_hotels;

USE project_hotels;


DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,  
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	phone VARCHAR(30) NOT NULL UNIQUE,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
);

DROP TABLE IF EXISTS profiles;
CREATE TABLE profiles (
	user_id INT UNSIGNED NOT NULL PRIMARY KEY,
	sex CHAR(1) NOT NULL,
	birthday DATE,
	hometown VARCHAR(100)
);

DROP TABLE IF EXISTS properties;
CREATE TABLE properties(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	city_id INT UNSIGNED NOT NULL,
	country_id INT UNSIGNED NOT NULL,
	airport_id INT UNSIGNED NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	phone VARCHAR(30) NOT NULL UNIQUE,
	property_type_id INT UNSIGNED NOT NULL,
	reserve_policy_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS cities;
CREATE TABLE cities(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	city VARCHAR(255),
	country_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS countries;
CREATE TABLE countries(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	country VARCHAR(255)
);

DROP TABLE IF EXISTS airports;
CREATE TABLE airports(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	airport_name VARCHAR(255),
	country_id INT UNSIGNED NOT NULL,
	city_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS property_types;
CREATE TABLE property_types( 
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	types VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS reserve_policy;
CREATE TABLE reserve_policy(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	policy VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS accommodation;
CREATE TABLE accommodation(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	max_guests_count INT NOT NULL,
	rooms_count INT,
	beds_count INT NOT NULL,
	bed_type_id INT UNSIGNED NOT NULL,
	baths_count INT,
	balcony BOOLEAN,
	meal_type_id INT UNSIGNED NOT NULL
);

DROP TABLE IF EXISTS bed_types;
CREATE TABLE bed_types(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	types VARCHAR(255)
);

DROP TABLE IF EXISTS meal_types;
CREATE TABLE meal_types(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	types VARCHAR(255)
);

DROP TABLE IF EXISTS reserve;
CREATE TABLE reserve(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED NOT NULL,
	guests_count INT NOT NULL,
	accommodation_id INT UNSIGNED NOT NULL,
	check_in DATETIME DEFAULT CURRENT_TIMESTAMP,
	check_out DATETIME DEFAULT CURRENT_TIMESTAMP
);









	
